-- SIMULATED CRM schema. All tables are prefixed sim_ to mark them as simulated.
-- These tables hold synthetic data generated by analysis/crm_sim/generator.py.
-- They are NOT real CRM data.

CREATE TABLE IF NOT EXISTS sim_accounts (
    account_id   INTEGER PRIMARY KEY,
    industry     TEXT NOT NULL,
    region       TEXT NOT NULL,
    tier         TEXT NOT NULL,
    deployment   TEXT NOT NULL,
    arr_band     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sim_opportunities (
    opp_id        INTEGER PRIMARY KEY,
    account_id    INTEGER NOT NULL REFERENCES sim_accounts(account_id),
    amount        REAL NOT NULL,
    created_date  TEXT NOT NULL,
    closed_date   TEXT NOT NULL,
    stage_reached TEXT NOT NULL,
    competitor    TEXT NOT NULL,
    outcome       TEXT NOT NULL CHECK (outcome IN ('Won', 'Lost')),
    loss_reason   TEXT
);

CREATE TABLE IF NOT EXISTS sim_stage_history (
    opp_id      INTEGER NOT NULL REFERENCES sim_opportunities(opp_id),
    stage       TEXT NOT NULL,
    entered_at  TEXT NOT NULL,
    exited_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sim_usage_monthly (
    account_id        INTEGER NOT NULL REFERENCES sim_accounts(account_id),
    month             TEXT NOT NULL,
    service           TEXT NOT NULL,
    consumption_units REAL NOT NULL,
    active_users      INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS sim_renewals (
    account_id   INTEGER PRIMARY KEY REFERENCES sim_accounts(account_id),
    start_arr    REAL NOT NULL,
    expansion    REAL NOT NULL DEFAULT 0,
    contraction  REAL NOT NULL DEFAULT 0,
    churn        BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sim_releases (
    pm_team              TEXT NOT NULL,
    quarter              TEXT NOT NULL,
    sprint               INTEGER NOT NULL,
    planned_points       INTEGER NOT NULL,
    delivered_points     INTEGER NOT NULL,
    planned_release_date TEXT NOT NULL,
    actual_release_date  TEXT NOT NULL,
    on_time              BOOLEAN NOT NULL
);
